### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by digitallyserviced** [digitallyserviced/tdfgo#7]
Just some ideas for enhancements or features or changes...

- [ ] Caching fonts or bundling in small generated db?
- [ ] Specify font path with flag/argument `--fontDir`
- [ ] Add BLOCK font types
- [ ] and OUTLINE
- [ ] Document/comment library and/or separate from cli util
- [ ] Add your suggestion here!
